# Generated by Django 6.0.6 on 2026-08-12 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('vendor', models.CharField(choices=[('NOKIA', 'Nokia'), ('CISCO', 'Cisco'), ('CIENA', 'Ciena')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('topology', models.CharField(choices=[('B4A', 'B4A'), ('B4B', 'B4B'), ('B4C', 'B4C'), ('B4E', 'B4E')], max_length=10)),
                ('port_no', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('subnet_mask', models.PositiveSmallIntegerField(help_text='CIDR prefix length, e.g. 24 for a /24 subnet', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('gateway', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
