# Generated by Django 6.0.6 on 2026-09-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_configjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer_vrf_id',
            field=models.CharField(blank=True, help_text='VPRN service id (edge roles only)', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='local_as',
            field=models.PositiveIntegerField(blank=True, help_text='BGP AS number (core/border roles)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='system_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Loopback/system interface IP', null=True),
        ),
    ]
