# Generated by Django 6.0.6 on 2026-09-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_device_customer_vrf_id_device_local_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer_vrf_name',
            field=models.CharField(blank=True, help_text='VRF name (edge roles only)', max_length=100),
        ),
    ]
