# Generated by Django 6.0.6 on 2026-09-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_alter_device_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
